### ISSUE TITLE
Почему middleware

### ISSUE THREAD

**Issue by vickodin** [BrandyMint/walletone#10]
Подскажите пожалуйста, а в чем плюс использования rack middleware при реализации подобной задачи?

**Comment by dapi** [comment]
Плюсы относительно чего?

**Comment by vickodin** [comment]
Подключение платежного агрегатора - это взаимодействие с ним в виде пары обычных запросов.
Зачем нам встраивание лишнего обработчика в стек обработки всех запросов к нашему приложению? Какой плюс от такого подхода, вместо вызова нужных функций в нужном нам контроллере?
Спасибо!

**Comment by dapi** [comment]
Понял. Это представляется как неплохой способ иметь универсальное решение не зависимое от rails/не rails.

Какие возможны варианты?
