### ISSUE TITLE
Не могу поставить ваш middleware

### ISSUE THREAD

**Issue by zeuslocker** [BrandyMint/walletone#13]
Здравствуйте, я не понимаю как прикрутить этот мидлвар к своему проекту, я создал папку app/middleware
закинул туда содержание walletone/lib/ c репозитория, и там же создал клас наследник 
Wonemid < Walletone::Middleware::Base
в application.rb добавил config.middleware.use "Wonemid"(Вариант N2 из readme)
но не совсем понятно как нужно переопределить метод perform к тому же при запуске сервера вылетает ошибка cannot load such file — virtus (LoadError)
Я создавал вопрос на stackoewrflow: 
http://stackoverflow.com/questions/41311657/include-wallet-one-middleware-rails
Вот ссылка на мой проект, возможно чем то поможет:
https://github.com/zeuslocker/rshop
Это небольшой магазин
Rails 5.0.0.1
postgresql-9.6

**Comment by nikolaokonesh** [comment]
@zeuslocker разобрались ли с middleware? Если да то какой вариант вы использовали

**Comment by sokyrko** [comment]
Не надо было ничего копировать. Просто создаешь там свой файл с содержимым, как в readme и регистрируешь в роутах. Всё.
