### ISSUE TITLE
WMI_INVOICE_OPERATIONS

### ISSUE THREAD

**Issue by arturaum** [BrandyMint/walletone#14]
Здравствуйте!

Коллбек немного обновился. Приходила рассылка от сервиса:

> Уважаемые пользователи!
> С 21 сентября 2017 года изменится состав коллбэка. В него будет включен новый параметр WMI_INVOICE_OPERATIONS. Для проверки цифровой подписи необходимо его учитывать.
> 
> Wallet One Team.

Будет ли обновление гема?

**Comment by dapi** [comment]
Добрый день!

Будет. За одно появится WMI_ORDER_ITEMS

**Comment by arturaum** [comment]
А когда примерно?

**Comment by arturaum** [comment]
Нам сказали нужно настроить отправку фискальных чеков в соответствии с 54-ФЗ до нового года.

**Comment by dapi** [comment]
К сожалению gem этот мы больше не поддерживаем я думаю вам проще самому внести нужные изменения, там достаточно добавить одно поле со списком товаров.

**Comment by dapi** [comment]
@arturaum тут выдержка кода по работе с Walletone которая у нас сейчас используется - https://github.com/BrandyMint/w1

Вот тут начинается добавление товаров в форму для чека - https://github.com/BrandyMint/w1/blob/master/lib/form_options.rb#L39

**Comment by dapi** [comment]
Присылайте PR, приму

**Comment by arturaum** [comment]
@dapi спасибо!
